pipeline:
  name: cleanup-job
  identifier: cleanupjob
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deploy
        identifier: Deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: NativeHelm
          service:
            serviceRef: cronService
          environment:
            environmentRef: Dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: K8Scronjobinfra
          execution:
            steps:
              - step:
                  type: K8sApply
                  name: cronjob
                  identifier: cronjob
                  spec:
                    skipDryRun: true
                    skipSteadyStateCheck: false
                    skipRendering: false
                    overrides: []
                    manifestSource:
                      type: K8sManifest
                      spec:
                        store:
                          type: Github
                          spec:
                            connectorRef: ycj_gitconnector
                            paths:
                              - cronjob-manifest.yaml
                            gitFetchType: Branch
                            branch: main
                            repoName: Harness_CronJob
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Helm Rollback
                  identifier: helmRollback
                  type: HelmRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
